name: tuktuk
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^6.0.0
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.5.0
  flutter_animate: ^4.2.0+1
  getwidget: ^4.0.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  country_picker: ^2.0.21
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/lilitaone.ttf

  assets:
    - assets/images/logo/
    - assets/images/tuktuk/
